"""add document_chunks table

Revision ID: 069eb7bec6fe
Revises: bcc0f29b0d11
Create Date: 2026-08-20 11:30:07.967936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '069eb7bec6fe'
down_revision: Union[str, Sequence[str], None] = 'bcc0f29b0d11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_chunks',
    sa.Column('paper_id', sa.Uuid(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('section_path', sa.String(length=512), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('token_estimate', sa.Integer(), nullable=False),
    sa.Column('is_embedded', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_document_chunks_embedded', 'document_chunks', ['is_embedded'], unique=False)
    op.create_index('ix_document_chunks_paper_index', 'document_chunks', ['paper_id', 'chunk_index'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_document_chunks_paper_index', table_name='document_chunks')
    op.drop_index('ix_document_chunks_embedded', table_name='document_chunks')
    op.drop_table('document_chunks')
    # ### end Alembic commands ###
