"""add paper_assets and ocr page count

Revision ID: 0f55665542f7
Revises: 6f944dd91239
Create Date: 2026-08-13 00:45:22.683231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f55665542f7'
down_revision: Union[str, Sequence[str], None] = '6f944dd91239'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paper_assets',
    sa.Column('paper_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('TABLE', 'FIGURE', 'EQUATION', name='asset_kind'), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('storage_key', sa.String(length=512), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_paper_assets_paper_kind', 'paper_assets', ['paper_id', 'kind'], unique=False)
    op.add_column('papers', sa.Column('ocr_page_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('papers', 'ocr_page_count')
    op.drop_index('ix_paper_assets_paper_kind', table_name='paper_assets')
    op.drop_table('paper_assets')
    # ### end Alembic commands ###
