"""extend papers with source file and extraction fields

Revision ID: 6f944dd91239
Revises: a438a86a67c3
Create Date: 2026-08-13 00:34:47.524930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f944dd91239'
down_revision: Union[str, Sequence[str], None] = 'a438a86a67c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('papers', sa.Column('original_filename', sa.String(length=512), nullable=False))
    op.add_column('papers', sa.Column('content_type', sa.String(length=128), nullable=False))
    op.add_column('papers', sa.Column('checksum', sa.String(length=64), nullable=False))
    op.add_column('papers', sa.Column('size_bytes', sa.BigInteger(), nullable=False))
    op.add_column('papers', sa.Column('storage_key', sa.String(length=512), nullable=False))
    op.add_column('papers', sa.Column('page_count', sa.Integer(), nullable=True))
    op.add_column('papers', sa.Column('abstract', sa.Text(), nullable=True))
    op.add_column('papers', sa.Column('authors', sa.Text(), nullable=True))
    op.add_column('papers', sa.Column('error_message', sa.Text(), nullable=True))
    op.create_index(op.f('ix_papers_checksum'), 'papers', ['checksum'], unique=False)
    op.create_index('uq_papers_workspace_checksum', 'papers', ['workspace_id', 'checksum'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_papers_workspace_checksum', table_name='papers')
    op.drop_index(op.f('ix_papers_checksum'), table_name='papers')
    op.drop_column('papers', 'error_message')
    op.drop_column('papers', 'authors')
    op.drop_column('papers', 'abstract')
    op.drop_column('papers', 'page_count')
    op.drop_column('papers', 'storage_key')
    op.drop_column('papers', 'size_bytes')
    op.drop_column('papers', 'checksum')
    op.drop_column('papers', 'content_type')
    op.drop_column('papers', 'original_filename')
    # ### end Alembic commands ###
