"""add paper_references table

Revision ID: bcc0f29b0d11
Revises: 0f55665542f7
Create Date: 2026-08-20 11:26:42.285616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcc0f29b0d11'
down_revision: Union[str, Sequence[str], None] = '0f55665542f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paper_references',
    sa.Column('paper_id', sa.Uuid(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('doi', sa.String(length=255), nullable=True),
    sa.Column('arxiv_id', sa.String(length=64), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_paper_references_arxiv_id', 'paper_references', ['arxiv_id'], unique=False)
    op.create_index('ix_paper_references_doi', 'paper_references', ['doi'], unique=False)
    op.create_index('ix_paper_references_paper_order', 'paper_references', ['paper_id', 'order'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_paper_references_paper_order', table_name='paper_references')
    op.drop_index('ix_paper_references_doi', table_name='paper_references')
    op.drop_index('ix_paper_references_arxiv_id', table_name='paper_references')
    op.drop_table('paper_references')
    # ### end Alembic commands ###
